# Generated by Django 4.2.8 on 2024-11-08 14:29

from django.db import migrations

def populate_null_values(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    Product.objects.filter(sku__isnull=True).update(sku='')
    Product.objects.filter(publisher__isnull=True).update(publisher='')

def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_cover_alter_product_publisher_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_null_values, reverse_populate),
    ]
