# Generated by Django 4.2.8 on 2024-11-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20241108_1542'),
    ]

    operations = [
    ]
