# Generated by Django 4.2.8 on 2024-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20241108_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=254),
        ),
    ]
