# Generated by Django 4.2.8 on 2024-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_publisher_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
