# Generated by Django 4.2.8 on 2024-11-09 10:19

from django.db import migrations

def populate_null_values(apps, schema_editor):
    Author = apps.get_model('products', 'Author')
    Author.objects.filter(friendly_name__isnull=True).update(friendly_name='')

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_author_friendly_name'),
    ]

    operations = [
        migrations.RunPython(populate_null_values, reverse_populate),
    ]
