# Generated by Django 4.2.8 on 2024-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20241109_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friendly_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
